# Generated by Django 4.2.16 on 2024-10-07 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('glyphs', '0002_tag_author_tag_author_ip_tag_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glyph',
            name='kage',
        ),
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='kage',
            field=models.TextField(blank=True),
        ),
    ]
